<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Acl\Controller\GruposController'     => __DIR__ . '/src/Acl/Controller/GruposController.php',
    'Acl\Controller\PermissoesController' => __DIR__ . '/src/Acl/Controller/PermissoesController.php',
    'Acl\Controller\RecursosController'   => __DIR__ . '/src/Acl/Controller/RecursosController.php',
    'Acl\Entity\Grupo'                    => __DIR__ . '/src/Acl/Entity/Grupo.php',
    'Acl\Entity\Permissao'                => __DIR__ . '/src/Acl/Entity/Permissao.php',
    'Acl\Entity\Recurso'                  => __DIR__ . '/src/Acl/Entity/Recurso.php',
    'Acl\Form\Grupo'                      => __DIR__ . '/src/Acl/Form/Grupo.php',
    'Acl\Form\GrupoFilter'                => __DIR__ . '/src/Acl/Form/GrupoFilter.php',
    'Acl\Form\Permissao'                  => __DIR__ . '/src/Acl/Form/Permissao.php',
    'Acl\Form\PermissaoFilter'            => __DIR__ . '/src/Acl/Form/PermissaoFilter.php',
    'Acl\Form\Recurso'                    => __DIR__ . '/src/Acl/Form/Recurso.php',
    'Acl\Form\RecursoFilter'              => __DIR__ . '/src/Acl/Form/RecursoFilter.php',
    'Acl\Module'                          => __DIR__ . '/Module.php',
    'Acl\Permissions\Acl'                 => __DIR__ . '/src/Acl/Permissions/Acl.php',
    'Acl\Repository\GrupoRepository'      => __DIR__ . '/src/Acl/Repository/GrupoRepository.php',
    'Acl\Repository\RecursoRepository'    => __DIR__ . '/src/Acl/Repository/RecursoRepository.php',
    'Acl\Service\Grupo'                   => __DIR__ . '/src/Acl/Service/Grupo.php',
    'Acl\Service\Permissao'               => __DIR__ . '/src/Acl/Service/Permissao.php',
    'Acl\Service\Recurso'                 => __DIR__ . '/src/Acl/Service/Recurso.php',
);
